### ISSUE TITLE
console input issue

### ISSUE THREAD

**Issue by omegatao** [gabrielhamel/WoT-Console-Mod#1]
There is a bug in the console, when I input text and encounter the letter 'a', the previously inputted text in the console will be immediately cleared.
My WOT version: 1.20.0.1

**Comment by gabrielhamel** [comment]
Oh hi =), I will look soon

**Comment by gabrielhamel** [comment]
Can you make a gif/picture or write me exactly what you input ? I can't reproduce this behavior
